In [1]:
import torch
torch.__version__

'2.0.1+cpu'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar.ndim)

0


In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [8]:
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
print(MATRIX.shape)

torch.Size([2, 2])


In [12]:
print(torch.rand(size = (1,2,3)))

tensor([[[0.0144, 0.6833, 0.5644],
         [0.5032, 0.9834, 0.5034]]])


In [13]:
tmp = torch.arange(1,5,0.1)
print(tmp)

tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000, 2.7000,
        2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000,
        3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000, 4.5000,
        4.6000, 4.7000, 4.8000, 4.9000])


In [16]:
print(tmp.sum()  )
print(tmp.max()  )
print(tmp.min()  )
print(tmp.mean() )

tensor(118.)
tensor(4.9000)
tensor(1.)
tensor(2.9500)
